spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(ekv/VUe7HhwM67Oa02MTFAaPrCbaUdC3W62e3leZPPw5RwjBCwt3P2VEpb56Nj1kU7ObEBXVfVnOOorGzfQLy4qs440WVjhahpUuCxmwOWA/mH8rF+c8QTLZ6HWZbM996IxKlAfTGo0+COwzGNqqn/WWsgvTJghkHUYKH54FIXdaXRQ9ypkGmt6hjgOgVCaxRBymSK2GabM=)
    username: ENC(GL1xAodxcTPQjpU5+ws/g+ZutpHB8BAq)
    password: ENC(AxReQZarV8HYCA3BKY3dizvA1jbwBW9w)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
jwt:
  token:
    secret-key: ENC(ncp6FR4Sg50kNvnSm+MZ8lWJ4jWZy876)
    expTime: ENC(IU7S5s6TbZRDtn+kdpj5Yw==)
    issuer: ENC(gshnN3M5dAh0OrQm0JmpOYiO+M+IMwi/)
logging:
  config: classpath:logback-prod.xml
sentry:
  dsn: ENC(FMK6bFLWfLNhD/VCmbDYw0Wjhi7MyOdJC98Zd84llM2ceysGq2gdrD5Ts+3lHoJqJrAHWPi0V4Ng9/Jt0nx9TAz4+aUuKKH4v0ieOehAUvpQPlTbvl79KA==)
  traces-sample-rate: 1.0
allow-ip: "http://gunimon.iptime.org:3000"